version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Password
      - DB_SERVER=mssql-container
      - DB_DATABASE=TestDB
      - DB_PORT=1433
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: YourStrong!Password
    ports:
      - "1433:1433"
